//! AI Engine for on-device word definitions
//!
//! This module provides the AI inference engine for generating word definitions
//! using on-device LLM models (Qwen3.5-0.8B).

use crate::core::error::Result;

/// AI Engine trait for word definition generation
pub trait AiEngine: Send + Sync {
    /// Generate a definition for a word given its context
    /// 
    /// # Arguments
    /// * `word` - The word to define
    /// * `context` - Optional surrounding text for context-aware definitions
    /// 
    /// # Returns
    /// The AI-generated definition as a String
    fn generate_definition(&self, word: &str, context: Option<&str>) -> Result<String>;
    
    /// Check if the AI engine is ready (model loaded)
    fn is_ready(&self) -> bool;
    
    /// Load the AI model (lazy loading)
    fn load_model(&mut self) -> Result<()>;
    
    /// Unload the AI model to free memory
    fn unload_model(&mut self);
}

/// Mock AI engine for testing and fallback
/// 
/// This engine provides simulated AI responses for testing purposes
/// and as a fallback when the real model is unavailable.
pub struct MockAiEngine {
    loaded: bool,
}

impl MockAiEngine {
    /// Create a new mock AI engine
    pub fn new() -> Self {
        Self { loaded: false }
    }
}

impl Default for MockAiEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl AiEngine for MockAiEngine {
    fn generate_definition(&self, word: &str, _context: Option<&str>) -> Result<String> {
        if !self.loaded {
            return Err(crate::core::error::ShuseiError::Internal(
                "AI engine not loaded".to_string()
            ));
        }
        
        // Mock definitions for testing
        let mock_definition = match word.to_lowercase().as_str() {
            "test" => "A procedure intended to establish the quality, performance, or reliability of something, especially before it is taken into use.".to_string(),
            "example" => "A thing characteristic of its kind or illustrating a general rule.".to_string(),
            "word" => "A single distinct meaningful element of speech or writing.".to_string(),
            "definition" => "A statement of the exact meaning of a word, especially in a dictionary.".to_string(),
            "context" => "The circumstances that form the setting for an event, statement, or idea, and in terms of which it can be fully understood.".to_string(),
            _ => format!("[Mock AI] Definition for '{}': This is a simulated definition for testing purposes. In production, this would be generated by the Qwen3.5-0.8B model.", word),
        };
        
        Ok(mock_definition)
    }
    
    fn is_ready(&self) -> bool {
        self.loaded
    }
    
    fn load_model(&mut self) -> Result<()> {
        log::info!("Mock AI engine: Model loaded (simulated)");
        self.loaded = true;
        Ok(())
    }
    
    fn unload_model(&mut self) {
        log::info!("Mock AI engine: Model unloaded");
        self.loaded = false;
    }
}

/// Word definition service
/// 
/// High-level service for managing word definitions with AI assistance
pub struct WordDefinitionService<E: AiEngine> {
    engine: E,
}

impl<E: AiEngine> WordDefinitionService<E> {
    /// Create a new word definition service
    pub fn new(engine: E) -> Self {
        Self { engine }
    }
    
    /// Get a reference to the AI engine
    pub fn engine(&self) -> &E {
        &self.engine
    }
    
    /// Get a mutable reference to the AI engine
    pub fn engine_mut(&mut self) -> &mut E {
        &mut self.engine
    }
    
    /// Generate and cache a word definition
    /// 
    /// This is the main entry point for tap-to-define functionality.
    /// It generates a definition using the AI engine and returns it.
    /// The caller is responsible for caching it in the database.
    pub fn define_word(&mut self, word: &str, context: Option<&str>) -> Result<String> {
        if !self.engine.is_ready() {
            log::warn!("AI engine not ready, attempting to load model");
            self.engine.load_model()?;
        }
        
        let definition = self.engine.generate_definition(word, context)?;
        log::info!("Generated definition for word '{}': {} chars", word, definition.len());
        
        Ok(definition)
    }
}

impl<E: AiEngine + Default> Default for WordDefinitionService<E> {
    fn default() -> Self {
        Self::new(E::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mock_ai_engine_creation() {
        let engine = MockAiEngine::new();
        assert!(!engine.is_ready());
    }

    #[test]
    fn test_mock_ai_engine_load_unload() {
        let mut engine = MockAiEngine::new();
        
        // Load model
        engine.load_model().unwrap();
        assert!(engine.is_ready());
        
        // Unload model
        engine.unload_model();
        assert!(!engine.is_ready());
    }

    #[test]
    fn test_mock_ai_engine_generate_definition() {
        let mut engine = MockAiEngine::new();
        engine.load_model().unwrap();
        
        // Test known words
        let definition = engine.generate_definition("test", None).unwrap();
        assert!(definition.contains("procedure"));
        
        let definition = engine.generate_definition("example", None).unwrap();
        assert!(definition.contains("characteristic"));
    }

    #[test]
    fn test_mock_ai_engine_unknown_word() {
        let mut engine = MockAiEngine::new();
        engine.load_model().unwrap();
        
        let definition = engine.generate_definition("unknown_word_xyz", None).unwrap();
        assert!(definition.contains("Mock AI"));
        assert!(definition.contains("unknown_word_xyz"));
    }

    #[test]
    fn test_mock_ai_engine_fails_when_not_loaded() {
        let engine = MockAiEngine::new();
        
        let result = engine.generate_definition("test", None);
        assert!(result.is_err());
    }

    #[test]
    fn test_word_definition_service() {
        let mut service = WordDefinitionService::new(MockAiEngine::new());
        
        // Service should auto-load on first use
        let definition = service.define_word("test", None).unwrap();
        assert!(definition.len() > 0);
    }

    #[test]
    fn test_word_definition_service_with_context() {
        let mut service = WordDefinitionService::new(MockAiEngine::new());
        
        let definition = service.define_word("context", Some("This is a test sentence with context."))
            .unwrap();
        assert!(definition.len() > 0);
    }

    #[test]
    fn test_word_definition_service_default() {
        let mut service = WordDefinitionService::<MockAiEngine>::default();
        
        let definition = service.define_word("word", None).unwrap();
        assert!(definition.contains("distinct meaningful element"));
    }

    #[test]
    fn test_mock_ai_definition_lengths() {
        let mut engine = MockAiEngine::new();
        engine.load_model().unwrap();
        
        // All definitions should be reasonably sized
        let words = vec!["test", "example", "word", "definition", "context"];
        for word in words {
            let definition = engine.generate_definition(word, None).unwrap();
            assert!(definition.len() > 20, "Definition too short for {}", word);
            assert!(definition.len() < 500, "Definition too long for {}", word);
        }
    }
}
